// Mock data utilities for rapid UI/UX theming without database dependencies
// Opt-in ONLY. Never infer this from missing/placeholder env vars, and never
// allow it in a production build: this flag disables the admin auth guard
// (see app/(admin)/admin/layout.js), so inferring it makes the app fail open.
export const IS_MOCK_MODE =
  process.env.NODE_ENV !== "production" &&
  process.env.NEXT_PUBLIC_MOCK_MODE === "true";

export const DEFAULT_MOCK_PLAYER = {
  id: "mock-player-1",
  name: "Cyber Alchemist",
};

export const DEFAULT_MOCK_TEAM = {
  id: "mock-team-1",
  name: "Steam Coders",
  lab: 1,
  score: 1250,
  player_count: 3,
};

export const MOCK_CATEGORIES_DATA = {
  "Frontend Frameworks": ["React", "Vue", "Svelte", "Angular"],
  "Databases": ["PostgreSQL", "MongoDB", "Redis", "Cassandra"],
  "CSS Units": ["rem", "vh", "em", "px"],
  "Programming Languages": ["Python", "Rust", "TypeScript", "Go"],
  "Browser Dev Tools": ["Console", "Network", "Elements", "Sources"],
  "Web Security Threats": ["XSS", "CSRF", "SQL Injection", "Man-in-the-Middle"],
  "Cloud Providers": ["AWS", "GCP", "Azure", "DigitalOcean"],
  "Protocols": ["HTTP", "WebSocket", "gRPC", "MQTT"],
  "Version Control": ["Git", "SVN", "Mercurial", "Perforce"],
  "Software Testing Tools": ["Jest", "Cypress", "Selenium", "Playwright"],
};

export const MOCK_SESSION = {
  id: "mock-session-1",
  status: "active",
  start_time: new Date().toISOString(),
  category1: "Frontend Frameworks",
  category2: "Databases",
  category3: "CSS Units",
  category4: "Programming Languages",
  lab: 1,
};

export const MOCK_UPCOMING_SESSION = {
  id: "mock-session-upcoming",
  status: "scheduled",
  start_time: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
  category1: "Browser Dev Tools",
  category2: "Web Security Threats",
  category3: "Cloud Providers",
  category4: "Protocols",
  lab: 1,
};

export const MOCK_TEAMS = [
  {
    id: "mock-t1",
    name: "Steam Coders",
    passkey: "WS-7K39",
    lab: 1,
    participant1_name: "Aaditya S",
    participant2_name: "Abhinav B",
    participant1_score: 950,
    participant2_score: 850,
    codections_score: 1800,
    r1_web_ui: 28,
    r1_web_ux: 32,
    r1_web_tech: 34,
    r1_web_total: 94,
    bidding_score: 45,
    r1_total_score: 1939,
    is_r2_qualified: true,
    r2_accuracy: 29,
    r2_responsiveness: 19,
    r2_code_quality: 18,
    r2_communication: 14,
    r2_aura_points: 95,
    r2_total_score: 95,
    grand_total_score: 2034,
    score: 1800,
    player_count: 2,
  },
  {
    id: "mock-t2",
    name: "Gear Hackers",
    passkey: "WS-4N81",
    lab: 1,
    participant1_name: "Abishek R",
    participant2_name: "Adhithya M",
    participant1_score: 820,
    participant2_score: 780,
    codections_score: 1600,
    r1_web_ui: 26,
    r1_web_ux: 30,
    r1_web_tech: 31,
    r1_web_total: 87,
    bidding_score: 30,
    r1_total_score: 1717,
    is_r2_qualified: true,
    r2_accuracy: 27,
    r2_responsiveness: 18,
    r2_code_quality: 17,
    r2_communication: 13,
    r2_aura_points: 90,
    r2_total_score: 89,
    grand_total_score: 1806,
    score: 1600,
    player_count: 2,
  },
  {
    id: "mock-t3",
    name: "Volt Voyagers",
    passkey: "WS-9B12",
    lab: 2,
    participant1_name: "Agash K",
    participant2_name: "Ajay G",
    participant1_score: 750,
    participant2_score: 700,
    codections_score: 1450,
    r1_web_ui: 24,
    r1_web_ux: 28,
    r1_web_tech: 30,
    r1_web_total: 82,
    bidding_score: 20,
    r1_total_score: 1552,
    is_r2_qualified: true,
    r2_accuracy: 25,
    r2_responsiveness: 16,
    r2_code_quality: 16,
    r2_communication: 12,
    r2_aura_points: 85,
    r2_total_score: 82,
    grand_total_score: 1634,
    score: 1450,
    player_count: 2,
  },
  {
    id: "mock-t4",
    name: "Clockwork Devs",
    passkey: "WS-3M56",
    lab: 1,
    participant1_name: "Akash S",
    participant2_name: "Akshaya V",
    participant1_score: 680,
    participant2_score: 620,
    codections_score: 1300,
    r1_web_ui: 23,
    r1_web_ux: 27,
    r1_web_tech: 28,
    r1_web_total: 78,
    bidding_score: 15,
    r1_total_score: 1393,
    is_r2_qualified: false,
    r2_accuracy: 0,
    r2_responsiveness: 0,
    r2_code_quality: 0,
    r2_communication: 0,
    r2_aura_points: 100,
    r2_total_score: 0,
    grand_total_score: 1393,
    score: 1300,
    player_count: 2,
  },
  {
    id: "mock-t5",
    name: "Brass Byte",
    passkey: "WS-8R24",
    lab: 2,
    participant1_name: "Anand R",
    participant2_name: "Anirudh K",
    participant1_score: 600,
    participant2_score: 550,
    codections_score: 1150,
    r1_web_ui: 21,
    r1_web_ux: 25,
    r1_web_tech: 26,
    r1_web_total: 72,
    bidding_score: -10,
    r1_total_score: 1212,
    is_r2_qualified: false,
    r2_accuracy: 0,
    r2_responsiveness: 0,
    r2_code_quality: 0,
    r2_communication: 0,
    r2_aura_points: 100,
    r2_total_score: 0,
    grand_total_score: 1212,
    score: 1150,
    player_count: 2,
  },
  {
    id: "mock-t6",
    name: "Iron Logic",
    passkey: "WS-2X77",
    lab: 2,
    participant1_name: "Arun Kumar",
    participant2_name: null,
    participant1_score: 500,
    participant2_score: 0,
    codections_score: 500,
    r1_web_ui: 20,
    r1_web_ux: 22,
    r1_web_tech: 24,
    r1_web_total: 66,
    bidding_score: 5,
    r1_total_score: 571,
    is_r2_qualified: false,
    r2_accuracy: 0,
    r2_responsiveness: 0,
    r2_code_quality: 0,
    r2_communication: 0,
    r2_aura_points: 100,
    r2_total_score: 0,
    grand_total_score: 571,
    score: 500,
    player_count: 1,
  },
];

export const MOCK_SESSIONS = [
  {
    id: "mock-s1",
    status: "active",
    start_time: new Date().toISOString(),
    lab: 1,
    category1: "Frontend Frameworks",
    category2: "Databases",
    category3: "CSS Units",
    category4: "Programming Languages",
  },
  {
    id: "mock-s2",
    status: "scheduled",
    start_time: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    lab: 1,
    category1: "Browser Dev Tools",
    category2: "Web Security Threats",
    category3: "Cloud Providers",
    category4: "Protocols",
  },
  {
    id: "mock-s3",
    status: "completed",
    start_time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    lab: 2,
    category1: "Version Control",
    category2: "Database Concepts",
    category3: "SDLC Methods",
    category4: "Software Testing Tools",
  },
];

export const MOCK_SUBMISSIONS = [
  { teamName: "Steam Coders", score: 950, timestamp: "Just now" },
  { teamName: "Gear Hackers", score: 870, timestamp: "2 mins ago" },
  { teamName: "Volt Voyagers", score: 720, timestamp: "5 mins ago" },
];

import initialCandidates from "./initialCandidates.json";

export const MOCK_CANDIDATES = initialCandidates;

